fixtures:
  forge_modules:
    apache:
      repo: 'puppetlabs-apache'
      ref:  '1.11.0'
    concat:
      repo: 'puppetlabs-concat'
      ref:  '2.2.0'
    mysql:
      repo: 'puppetlabs-mysql'
      ref:  '3.10.0'
    postgresql:
      repo: 'puppetlabs-postgresql'
      ref:  '4.8.0'
    ruby:
      repo: 'puppetlabs-ruby'
      ref:  '0.6.0'
    stdlib:
      repo: 'puppetlabs-stdlib'
      ref:  '4.15.0'
    vcsrepo:
      repo: 'puppetlabs-vcsrepo'
      ref:  '1.5.0'
  repositories:
    # none
  symlinks:
    puppetdashboard: "#{source_dir}"
